### ISSUE TITLE
Invalid Volume Specification Using Docker-Compose

### ISSUE THREAD

**Issue by intersectRaven** [slonopotamus/stevedore#38]
As of version 0.3.4, docker-compose mounting fails when the container has a directory mount.

![image](https://user-images.githubusercontent.com/229447/159636787-e37eebc4-06f8-4605-a065-413b664ce840.png)

![image](https://user-images.githubusercontent.com/229447/159637190-1641078b-f9c5-4007-8666-3c22b6af1194.png)

This is from Windows to Linux docker context.

**Comment by slonopotamus** [comment]
Fixed in just-released stevedore-0.4.0. Note that it takes some time before release becomes available via Chocolatey/WinGet.

**Comment by intersectRaven** [comment]
Problem still occurs if it is a file mount.

![image](https://user-images.githubusercontent.com/229447/159665567-455b181a-54e9-4356-9f2c-286c85223833.png)

**Comment by slonopotamus** [comment]
Hmm...

**Comment by intersectRaven** [comment]
![image](https://user-images.githubusercontent.com/229447/159668283-b797796f-33e1-4a26-bb69-370aed819f9f.png)

For me it is still invalid volume specification but maybe the directory being created is related so maybe solving that will also solve this.

**Comment by intersectRaven** [comment]
![image](https://user-images.githubusercontent.com/229447/159668790-de192c27-5c00-4c75-89b2-5580afb67aad.png)

Here is the compose entry for the container if it helps.

**Comment by intersectRaven** [comment]
![image](https://user-images.githubusercontent.com/229447/159671034-de895fed-050c-4cea-9cf2-409e27ddcc64.png)

The volumes should be these. I forgot that I already edited it to figure out what was not working.

**Comment by slonopotamus** [comment]
Right. Problematic syntax is `./<file>:/<file>`.

**Comment by slonopotamus** [comment]
I believe that single-file bind-mounts are fixed in Stevedore 0.4.1 (is being published currently).

**Comment by intersectRaven** [comment]
I can confirm it works now with no modifications to our compose. 😊
